### ISSUE TITLE
Syntax needs to be migrated to aioredis v2.0.0

### ISSUE THREAD

**Issue by AM2i9** [python-discord/async-rediscache#16]
Upon the release of [aioredis v2.0.0](https://github.com/aio-libs/aioredis-py/releases/tag/v2.0.0), the syntax for creating a connection has changed, which is causing the following error:
```
AttributeError: module 'aioredis' has no attribute 'create_redis_pool'
```
It can be solved by installing aioredis v1.3.1 manually, but pip installs v2.0.0, which could lead to problems.

Read here for more information on syntax changes:
https://aioredis.readthedocs.io/en/latest/migration/

**Comment by HassanAbouelela** [comment]
See #20 to track this issue. There's also a release candidate out now which uses redis-py (the successor to aioredis v2). [Release](https://github.com/SebastiaanZ/async-rediscache/releases/tag/v1.0.0-rc2), [PyPi](https://pypi.org/project/async-rediscache/1.0.0rc2/).

You can install it from pypi using:
```shell
pip install async-rediscache==1.0.0rc2
```
